name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Haal de code op uit de repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Stap 2: Stel Flutter in
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # Zorg ervoor dat dit overeenkomt met je Flutter versie

      # Stap 3: Installeer afhankelijkheden
      - name: Install dependencies
        run: flutter pub get

      # Stap 4: Voer widgettests uit
      - name: Run widget tests
        run: flutter test
